console_error_message: "This Command Can Be Used by Players Only"
permission_error: "&7[&5SE&7] &cYou Don't Have Sufficient Permission to execute this command"

commands:
  fly:
   fly_enable: "&7[&5SE&7] &eFlight Enabled"
   fly_disable: "&7[&5SE&7] &eFlight Disabled"

Events:
  first_join_message: '&a%player% &7 has Joined For The First Time!! &cWooHoo!'
  first_join_sound:
  join_message: '&7[&2&l+&7]&f %player%'
  leave_message: '&7[&c&l-&7]&f %player%'