name: SastaEssentials
version: 1.0
author: NYU19
main: me.nyu19.SastaEssentials.Main
description: This Plugin Is a Sasta Essentials

commands:
  fly:
    description: Toggles Flight
  reload:
    description: Reloads the Plugin
  heal:
    description: heals the Player
  god:
    aliases:
      - goddess
    description: Toggles God Mode
  flyspeed:
    description: Sets player Fly Speed